config/routes.php
<?php
/**
 * Routes configuration
 *
 * In this file, you set up routes to your controllers and their actions.
 * Routes are very important mechanism that allows you to freely connect
 * different URLs to chosen controllers and their actions (functions).
 *
 * CakePHP(tm) : Rapid Development Framework (https://cakephp.org)
 * Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @copyright     Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 * @link          https://cakephp.org CakePHP(tm) Project
 * @license       https://opensource.org/licenses/mit-license.php MIT License
 */

use Cake\Core\Plugin;
use Cake\Routing\RouteBuilder;
use Cake\Routing\Router;
use Cake\Routing\Route\DashedRoute;

/**
 * The default class to use for all routes
 *
 * The following route classes are supplied with CakePHP and are appropriate
 * to set as the default:
 *
 * - Route
 * - InflectedRoute
 * - DashedRoute
 *
 * If no call is made to `Router::defaultRouteClass()`, the class used is
 * `Route` (`Cake\Routing\Route\Route`)
 *
 * Note that `Route` does not do any inflections on URLs which will result in
 * inconsistently cased URLs when used with `:plugin`, `:controller` and
 * `:action` markers.
 *
 */
Router::defaultRouteClass(DashedRoute::class);

Router::scope('/', function (RouteBuilder $routes) {
    /**
     * Here, we are connecting '/' (base path) to a controller called 'Pages',
     * its action called 'display', and we pass a param to select the view file
     * to use (in this case, src/Template/Pages/home.ctp)...
     */
    $routes->connect('/', ['controller' => 'Contents', 'action' => 'page']);
    $routes->connect('/sliders', ['controller' => 'Sliders', 'action' => 'sliderlist']);
    $routes->connect('/documentguides', ['controller' => 'Documentguides', 'action' => 'doclist']);
    $routes->connect('/content-types', ['controller' => 'ContentTypes', 'action' => 'listPages']);
   $routes->connect('/ContentTypes', ['controller' => 'ContentTypes', 'action' => 'listPages']);
    $routes->connect('/backend', ['controller' => 'Users', 'action' => 'login']);
    $routes->connect('/login', ['controller' => 'Users', 'action' => 'customer_login']);
    /**
     * ...and connect the rest of 'Pages' controller's URLs.
     */
    //$routes->connect('/pages/*', ['controller' => 'Pages', 'action' => 'display']);

    /**
     * Connect catchall routes for all controllers.
     *
     * Using the argument `DashedRoute`, the `fallbacks` method is a shortcut for
     *    `$routes->connect('/:controller', ['action' => 'index'], ['routeClass' => 'DashedRoute']);`
     *    `$routes->connect('/:controller/:action/*', [], ['routeClass' => 'DashedRoute']);`
     *
     * Any route class can be used with this method, such as:
     * - DashedRoute
     * - InflectedRoute
     * - Route
     * - Or your own route class
     *
     * You can remove these routes once you've connected the
     * routes you want in your application.
     */
    $routes->fallbacks(DashedRoute::class);
});

/**
 * Load all plugin routes. See the Plugin documentation on
 * how to customize the loading of plugin routes.
 */
Plugin::routes();

src/Model/Table/AccountsTable.php
<?php
namespace App\Model\Table;

use Cake\ORM\Query;
use Cake\ORM\RulesChecker;
use Cake\ORM\Table;
use Cake\Validation\Validator;

/**
 * Accounts Model
 *
 * @property \App\Model\Table\RegisterationsTable|\Cake\ORM\Association\BelongsTo $Registerations
 * @property \App\Model\Table\PaymenttypesTable|\Cake\ORM\Association\BelongsTo $Paymenttypes
 * @property \App\Model\Table\UsersTable|\Cake\ORM\Association\BelongsTo $Users
 * @property \App\Model\Table\CommentsTable|\Cake\ORM\Association\HasMany $Comments
 *
 * @method \App\Model\Entity\Account get($primaryKey, $options = [])
 * @method \App\Model\Entity\Account newEntity($data = null, array $options = [])
 * @method \App\Model\Entity\Account[] newEntities(array $data, array $options = [])
 * @method \App\Model\Entity\Account|bool save(\Cake\Datasource\EntityInterface $entity, $options = [])
 * @method \App\Model\Entity\Account patchEntity(\Cake\Datasource\EntityInterface $entity, array $data, array $options = [])
 * @method \App\Model\Entity\Account[] patchEntities($entities, array $data, array $options = [])
 * @method \App\Model\Entity\Account findOrCreate($search, callable $callback = null, $options = [])
 *
 * @mixin \Cake\ORM\Behavior\TimestampBehavior
 */
class AccountsTable extends Table
{

    /**
     * Initialize method
     *
     * @param array $config The configuration for the Table.
     * @return void
     */
    public function initialize(array $config)
    {
        parent::initialize($config);

        $this->setTable('accounts');
        $this->setDisplayField('id');
        $this->setPrimaryKey('id');

        $this->addBehavior('Timestamp');

        $this->belongsTo('Registerations', [
            'foreignKey' => 'registeration_id',
            'joinType' => 'INNER'
        ]);
        $this->belongsTo('Paymenttypes', [
            'foreignKey' => 'paymenttype_id',
            'joinType' => 'INNER'
        ]);
        $this->belongsTo('Users', [
            'foreignKey' => 'user_id',
            'joinType' => 'INNER'
        ]);
        $this->hasMany('Comments', [
            'foreignKey' => 'account_id'
            , 'dependent' => true
        ]);
    }

    /**
     * Default validation rules.
     *
     * @param \Cake\Validation\Validator $validator Validator instance.
     * @return \Cake\Validation\Validator
     */
    public function validationDefault(Validator $validator)
    {
        $validator
            ->integer('id')
            ->allowEmpty('id', 'create');

        $validator
            ->scalar('amount_paid')
            ->requirePresence('amount_paid', 'create')
            ->notEmpty('amount_paid');

//        $validator
//            ->scalar('amount_due')
//            ->requirePresence('amount_due', 'create')
//            ->notEmpty('amount_due');

        $validator
            ->dateTime('amout_date')
            ->requirePresence('amout_date', 'create')
            ->notEmpty('amout_date');

        $validator
            ->dateTime('due_date')
            ->requirePresence('due_date', 'create')
            ->notEmpty('due_date');

//        $validator
//            ->integer('status')
//            ->requirePresence('status', 'create')
//            ->notEmpty('status');

        return $validator;
    }

    /**
     * Returns a rules checker object that will be used for validating
     * application integrity.
     *
     * @param \Cake\ORM\RulesChecker $rules The rules object to be modified.
     * @return \Cake\ORM\RulesChecker
     */
    public function buildRules(RulesChecker $rules)
    {
        $rules->add($rules->existsIn(['registeration_id'], 'Registerations'));
        $rules->add($rules->existsIn(['paymenttype_id'], 'Paymenttypes'));
        $rules->add($rules->existsIn(['user_id'], 'Users'));

        return $rules;
    }
}

src/Controller/AccountsController.php
<?php

namespace App\Controller;

use App\Controller\AppController;
use Cake\Datasource\ConnectionManager;
use Cake\ORM\TableRegistry;
use Cake\Mailer\Email;

/**
 * Accounts Controller
 *
 * @property \App\Model\Table\AccountsTable $Accounts
 *
 * @method \App\Model\Entity\Account[] paginate($object = null, array $settings = [])
 */
class AccountsController extends AppController {

    /**
     * Index method
     *
     * @return \Cake\Http\Response|void
     */
    // payment detail of individual registered members
    public function index($id = null) {
        $permission = $this->viewVars['actionPermission'];

        if ($permission == 1 || $permission == 2) {
            
        } else {
            return $this->redirect(['controller' => 'Pages', 'action' => 'welcome']);
        }
        $this->set(compact('permission'));
        if (!empty($_GET['id'])) {
            $id = $_GET['id'];
        }
        if ($id) {
            $this->paginate = [
                'contain' => ['Registerations', 'Paymenttypes', 'Users'],
                'conditions' => ['Accounts.Registeration_id' => $id],
            ];
            $us = $this->Accounts->find('all', array(
                        'contain' => ['Registerations', 'Paymenttypes', 'Users'],
                        'conditions' => ['Accounts.Registeration_id' => $id],
                        'order' => array('Accounts.id DESC')
                    ))->first();
        }

        $this->loadModel('Registerations');

        if ($id) {
            $user = $this->Registerations->find('all', array(
                        'contain' => 'Users',
                        'conditions' => ['Registerations.id' => $id],
                    ))->first();
        }


        if ($user != "") {
            $this->set(compact('user'));
        }
        $accounts = $this->paginate($this->Accounts);
        //debug($accounts);

        $this->set(compact('accounts', 'us'));
        $this->set('_serialize', ['accounts']);

        $this->viewBuilder()->setLayout('backend');
    }
// report can be generated here
    public function report() {
        $conn = ConnectionManager::get('default');
        $fields;
        $joins;
        $condition = 'u.role_id=6';

        $permission = $this->viewVars['actionPermission'];
        $this->set(compact('permission'));

        if ($this->request->is('post')) {
            if (!empty($this->request->data['search'])) {
                $search = str_replace(" ", "", $this->request->data['search']);
                $condition .= ' AND CONCAT(first_name, last_name) like "%' . $search . '%"';
                //$condition .= ' AND accounts.paymenttype_id=' . $this->request->data['pay'];
            }
            if (!empty($this->request->data['pay'])) {
                $condition .= ' AND a.paymenttype_id=' . $this->request->data['pay'];
            }

            if (isset($this->request->data['status'])) {

                if ($this->request->data['status'] == 0) {
                    $condition .= ' AND u.status = 2 AND r.status = 0';
                }
                if ($this->request->data['status'] == 2) {
                    $condition .= ' AND u.status <= 1 AND r.status = 0';
                }
                if ($this->request->data['status'] == 1) {
                    $condition .= ' AND u.status = 2  AND r.status = 1';
                }
            }
            if (!empty($this->request->data['amount_paid'])) {
                $condition .= ' AND a.amount_paid =' . $this->request->data['amount_paid'];
            }
            if (!empty($this->request->data['amount_due'])) {
                $condition .= ' AND a.amount_due=' . $this->request->data['amount_due'];
            }

            if (!empty($this->request->data['membertypes'])) {
                $condition .= ' AND r.membertype_id=' . $this->request->data['membertypes'];
            }

            if (!empty($this->request->data['to_amount_date']) && !empty($this->request->data['from_amount_date'])) {
                $condition .= ' AND DATE(a.amout_date) between "' . $this->request->data['from_amount_date'] . '" AND "' . $this->request->data['to_amount_date'] . '"';
            } else
            if (!empty($this->request->data['from_amount_date'])) {
                // $condition .= ' AND event_types.amount between ' . $minprice . ' AND ' . $maxprice
                $condition .= ' AND DATE(a.amout_date)=  "' . $this->request->data['from_amount_date'] . '"';
            }

            if (!empty($this->request->data['to_due_date']) && !empty($this->request->data['from_due_date'])) {
                $condition .= ' AND DATE(a.due_date) between "' . $this->request->data['from_due_date'] . '" AND "' . $this->request->data['to_due_date'] . '"';
            } else
            if (!empty($this->request->data['from_due_date'])) {
                // $condition .= ' AND event_types.amount between ' . $minprice . ' AND ' . $maxprice
                $condition .= ' AND DATE(a.due_date)= "' . $this->request->data['from_due_date'] . '"';
            }
            //            if (!empty($this->request->data['amount_due'])) {
            //                $condition .= 'accounts.amount_due=' . $this->request->data['amount_due'];
            //            }
        }
        if (isset($_GET['showdetails']) and $_GET['showdetails'] == 1) {
            $query = $conn->execute(
                    'SELECT  a.`registeration_id`, a.`amount_due` , u.`first_name` , u.`last_name` , u.`first_name` , p.`payment_name`, m.`description`, m.`name` , a.`amout_date`, a.`due_date`,a.`amount_paid`,m.`amount`'
                    //. $fields
                    . ' FROM users u  '
                    . 'inner join registerations r ON u.id= r.user_id '
                    . 'inner join accounts a ON r.id= a.registeration_id '
                    //. 'inner join comments ON accounts.id= comments.account_id '
                    . 'inner join paymenttypes p ON p.id = a.paymenttype_id '
                    . 'inner join membertypes m ON m.id= r.membertype_id '
                    //. $joins
                    . 'where ' . $condition . ' order by u.first_name ASC,u.last_name ASC,a.amount_due DESC  ');
        } else {
            $query = $conn->execute(
                    'SELECT  a.`registeration_id`, a.`amount_due` , u.`first_name` , u.`last_name` , u.`first_name` , p.`payment_name`, m.`description`, m.`name` , a.`amout_date`, a.`due_date`,a.`amount_paid`,m.`amount`'
                    //. $fields
                    . ' FROM accounts a  '
                    . 'inner join registerations r  ON r.id= a.registeration_id '
                    . 'inner join users u ON u.id= r.user_id '
                    //. 'inner join comments ON accounts.id= comments.account_id '
                    . 'inner join paymenttypes p ON p.id = a.paymenttype_id '
                    . 'inner join membertypes m ON m.id= r.membertype_id '
                    //. $joins
                    . 'where  a.id IN (
                SELECT MAX(id)
                FROM accounts 
                GROUP BY registeration_id
            ) AND ' . $condition . ' order by a.amount_due DESC ');
        }




        $results = $query->fetchAll('assoc');

        $this->loadModel('Membertypes');
        $membertypes = $this->Membertypes->find('list', ['limit' => 200]);

        $paymenttypes = $this->Accounts->Paymenttypes->find('list', ['limit' => 200, ['keyField' => 'id', 'valueField' => 'payment_name']]);
        $this->set(compact('results', 'paymenttypes', 'membertypes'));
        $this->viewBuilder()->setLayout('backend');
    }

    public function export($id = null) {
        if (!empty($_GET['id'])) {
            echo $id = $_GET['id'];
        }
        //        $this->paginate = [
        //            'contain' => ['Registerations', 'Paymenttypes', 'Users'],
        //            'conditions' => ['Accounts.registeration_id' => $id]
        //        ];
        //        $this->loadModel('Registerations');
        //         if ($id) {
        //            $user = $this->Registerations->find('all',array(
        //                'contain'=> 'Users',
        //    'conditions' => ['registerations.id' => $id],
        //    
        //))->first();
        //         }
        //           
        //           
        //        if ($user != "") {
        //            $this->set(compact('user'));
        //           
        //        }
        //        $accounts = $this->paginate($this->Accounts);
        $conn = ConnectionManager::get('default');
        $sql1 = "select * from accounts";

        $query = $conn->execute($sql1);

        $accounts = $query->fetchAll('assoc');

        $this->set(compact('accounts'));
        $this->set('_serialize', ['accounts']);

        $this->viewBuilder()->setLayout('backend');
    }

    public function changeStatus($id = null, $status = null) {
        $id = $_GET['id'];
        $accont_id = $_GET['accont_id'];
        $status = $_GET['status'];
        $regs = TableRegistry::get('Accounts');
        $reg = $regs->get($id);
        $reg->status = $status;
        if ($regs->save($reg)) {

            if ($reg->status == 1) {
                //                $email = new Email();
                //                $email->template('default', 'default')
                //                        ->emailFormat('html')
                //                        ->to($user->email)
                //                        ->from(['info@cyberclouds.com' => 'welvett.com'])
                //                        ->subject('Welvet Account Verified')
                //                        ->viewVars(['content' => $user])
                //                        ->send();
            }
            $this->Flash->success('status changed');
        } else {
            $this->Flash->error('status not changed');
        }
        //        if ($reg->role_id == 3) {

src/Template/Accounts/add.ctp
<?php
/**
  * @var \App\View\AppView $this
  */
$array = explode('/', $_SERVER['REQUEST_URI']);
$userId = end($array);
?>
<div class="panel-head-info">
    <p class="pull-left info-text">Ajouter le Paiement reçu - <strong><?php echo $user->user->first_name . ' '.$user->user->last_name ; ?></strong></p>
    <a href="<?php echo $this->request->webroot ?>accounts/index/<?php echo $userId;?>" style="font-size:14px;" class="btn btn-primary btn-blue-custom pull-right text-info"><i class="fa fa-angle-left"></i> Précédent</a>
    <div class="clearfix"></div>

</div>
<div class="users form">
    <?php echo $this->Form->create($account,array('type'=>'file','class'=>'form-horizontal','id'=>'UserAddForm')); ?>
    <fieldset>
        <div class="form-group required">
            <label for="title" class="col-md-2 control-label"> Type de Paiement</label>
            <div class="col-md-2" style="ma">

                <?php echo $this->Form->control('paymenttype_id',array('div'=>false,'label'=>false,'class'=>'form-control','required','options' => $paymenttypes,'default'=> '2')); ?>
                <?php echo $this->Form->control('registeration_id',array('type'=>'hidden','value' => $userId,'div'=>false,'label'=>false,'class'=>'form-control','required')); ?>
            </div> 
            <label for="title" class="col-md-2 control-label">Montant Payé</label>
            <div class="col-md-2">

                <?php echo $this->Form->control('amount_paid',array('div'=>false,'label'=>false,'class'=>'form-control','required','value'=>$amount));
                $userid = $this->request->session()->read('Auth.User.id');
                echo $this->Form->control('user_id', ['type' => 'hidden','value'=>$userid]);
                ?>
            </div> 
            <label for="title" class="col-md-2 control-label">Votre prochaine échéance</label>
            <div class="col-md-2">
                <?php  $args = array();
                echo $this->Form->input('due_date',array('options'=>$args,'default'=>'','div'=>false,'label'=>false,'class'=>'form-control','required', 'id' => 'year')); ?>
                <?php //echo $this->Form->control('due_date',array('div'=>false,'label'=>false,'class'=>'form-control datepicker','required','type'=>'text','value'=>$due_date)); ?>
            </div> 
        </div>  



        <div class="form-group required">
            <!--            <label for="title" class="col-md-3 control-label">Current Date</label>-->
            <div class="col-md-10">

                <?php  echo $this->Form->control('amount_date',array('div'=>false,'label'=>false,'class'=>'form-control','required','type'=>'hidden','value'=>date("Y-m-d"),'disabled')); ?>
            </div> 
        </div>

        <!--        <div class="form-group required">
<label for="title" class="col-md-3 control-label">Amount Due</label>
<div class="col-md-10">

<?php //echo $this->Form->control('amount_due',array('div'=>false,'label'=>false,'class'=>'form-control','required')); ?>
</div> 
</div>-->


    </fieldset>
    <fieldset>
        <div class="form-group required">
            <label for="title" class="col-md-3 control-label ">Commentaire</label>
            <div class="col-md-10">

                <?php echo $this->Form->control('comment',array('div'=>false,'label'=>false,'class'=>'form-control','type'=>'textarea','required')); ?>
                <?php $userid = $this->request->session()->read('Auth.User.id');
                echo $this->Form->control('user_id', ['type' => 'hidden','value'=>$userid]);
                ?>

            </div> 
        </div>  



    </fieldset>


    <div class="form-group">
        <div class="col-md-12 text-center">
            <?php 
            echo $this->Form->control('Ajouter le Paiement reçu',array('type'=>'submit','div'=>false,'label'=>false,'class'=>'btn btn-default btn-blue-custom btn-lg'));
            echo $this->Form->end(); ?>
        </div>
    </div>

</div>




</div>
<script>
    $("#UserAddForm").submit(function () {

    });
    $(document).ready(function(){
        var date = new Date();
        var year = date.getFullYear() - 1;
        var selectedDate = year + 2;
        var options = '<option value="">Select Year</option>';
        for(var i = 0; i < 3; i++){
            year = year + 1;
            options = options + '<option value="'+year+'">'+year+'</option>';

        }

        $('#year').html(options);
        $('#year').val(selectedDate);
    });
</script>

src/Template/Accounts/export.ctp
<?php
/**
  * @var \App\View\AppView $this
  * @var \App\Model\Entity\Account[]|\Cake\Collection\CollectionInterface $accounts
  */
//debug($accounts);exit;
$array = explode('/', $_SERVER['REQUEST_URI']);
$accId = end($array);

$filename = "accounts.csv";
$fp = fopen('php://output', 'w');

//$query = "SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='test2' AND TABLE_NAME='toy'";
//$result = mysqli_query($conn,$query);
//while ($row = mysqli_fetch_row($result)) {
//	$header[] = $row[0];
//}	

header('Content-type: application/csv');
header('Content-Disposition: attachment; filename='.$filename);
$heading='<b style="font-size:70px;"> this is some  csv stuff you know.</b>';

fputcsv($fp, array($heading));
fputcsv($fp, array('id','name', 'fist', 'you know.'));

foreach ($accounts as $account):
    
    fputcsv($fp, $account);
    
endforeach;
exit;
//$query = "SELECT * FROM toy";
//$result = mysqli_query($conn, $query);
while($row = mysqli_fetch_row($accounts)) {
	fputcsv($fp, $row);
}
exit;
?>
<div class="panel-head-info">
    <p class="pull-left info-text">Accounts - <strong><?php echo $user['user']['first_name'];echo " " ;?><?php echo $user['user']['last_name']; ?></strong></p>
            <!--<a href="<?php // echo $this->request->webroot ?>pages" style="font-size:14px;" class="btn btn-primary btn-blue-custom pull-right text-info"><i class="fa fa-angle-left"></i> Go Back</a>-->
    <div class="clearfix"></div>
    <?php 
//    if($permission == 2){
//    ?>
    
    <a href="<?php  echo $this->request->webroot ?>accounts/add/<?php echo $accId;?>" class="btn btn-success"><i class="fa fa-plus"></i> Add Accounts</a>
     <a href="<?php echo $this->request->webroot ?>registerations/index/<?php echo $accId;?>" style="font-size:14px;" class="btn btn-primary btn-blue-custom pull-right text-info"><i class="fa fa-angle-left"></i> Go Back</a>
     <a href="<?php echo $this->request->webroot ?>registerations/export/<?php echo $accId;?>" style="font-size:14px; margin-right: 10px; margin-top: 10px;" class="btn btn-primary btn-green-custom pull-right text-info"> Export</a>

</div>
     </br>

<div class="container-fluid content-container" style="">

    <div class="row">
        <div id="no-more-tables">
            <table class="col-md-12 table-bordered table-striped table-condensed cf" >
                <thead class="cf">
                    <tr>
                        
                       <th scope="col"><?= $this->Paginator->sort('id','Account id') ?></th>
                        <th scope="col"><?= $this->Paginator->sort('paymenttype_id','Payment Type') ?></th>
                        <th scope="col"><?= $this->Paginator->sort('amount_paid','Amount Paid') ?></th>
                        <th scope="col"><?= $this->Paginator->sort('amount_due','Amount Due') ?></th>
                        <th scope="col"><?= $this->Paginator->sort('amout_date','Amount Date') ?></th>
                        <th scope="col"><?= $this->Paginator->sort('due_date','Due Date') ?></th>
                        <th scope="col"><?= $this->Paginator->sort('user_id','Added By') ?></th>
                        <th scope="col"><?= $this->Paginator->sort('status','Status') ?></th>
                        <th scope="col"><?= $this->Paginator->sort('modified','Modified') ?></th>
                        <th scope="col" class="actions"><?= __('Actions') ?></th>
                   </tr>
                </thead>
                <tbody>
                       <?php foreach ($accounts as $account): ?>
            <tr>
                <td><?= h($account->id) ?></td>

                <td><?= h($account->paymenttype->payment_name)  ?></td>
                <td><?= h($account->amount_paid) ?></td>
                <td><?= h($account->amount_due) ?></td>
                <td><?= h(date('d.m.y',strtotime($account->amout_date))) ?></td>
                <td><?= h(date('d.m.y',strtotime($account->due_date))) ?></td>
                <td><?= $account->has('user') ? $this->Html->link($account->user->user_name, ['controller' => 'Users', 'action' => 'view', $account->user->id]) : '' ?></td>
                <td><?= $this->Number->format($account->status) ?></td>
                <td><?php echo h(date('d.m.y',strtotime($account->modified))); ?></td>
                <td class="actions">
                     <?php echo $this->Html->link(__('Comments'), array('controller' => 'Comments', 'action' => 'index','id' =>$account->id,'accont_id'=>$accId),array('class'=>'btn btn-primary','escape'=>false)); ?>

                    <?php 
                      // if($permission == 2){                                                                                              
                                
				echo $this->Html->link(__('<i class="fa fa-edit"></i> Edit'), array('controller' => 'accounts', 'action' => 'edit','id' =>$account->id,'accont_id'=>$accId),array('class'=>'btn btn-success','escape'=>false)); 
			
			
								echo $this->Form->postLink(__('<i class="fa fa-trash-o"></i> Delete'), ['action' => 'delete' ,'id' =>$account->id,'accont_id'=>$accId], ['escape'=>false,'class'=>'btn btn-danger','confirm' => __('Are you sure you want to delete # {0}?', $account->id)]);
                                                               // }
								//echo $this->Html->link(__('<i class="fa fa-trash"></i> Delete'), ['controller'=>'users','action' => 'delete', $user->id], ['escape'=>false,'class'=>'btn btn-danger','confirm' => __('Are you sure you want to delete # {0}?', $user->username)]);
                            
							//echo $this->Form->postLink(__('<i class="fa fa-trash"></i> Delete'), ['action' => 'delete', $user->id], ['escape'=>false,'class'=>'btn btn-danger','confirm' => __('Are you sure you want to delete # {0}?', $user->id)]); 
                                                       // } ?></td>
            </tr>
            <?php endforeach; ?>
                </tbody>
            </table>
            </form>
        </div>
    </div>

    <br />
    <div class="paginator">
        <ul class="pagination">
            <?php
                echo $this->Paginator->prev(__('prev'), array('tag' => 'li'), null, array('tag' => 'li','class' => 'disabled','disabledTag' => 'a'));
                echo $this->Paginator->numbers(array('separator' => '','currentTag' => 'a', 'currentClass' => 'active','tag' => 'li','first' => 1));
                echo $this->Paginator->next(__('next'), array('tag' => 'li','currentClass' => 'disabled'), null, array('tag' => 'li','class' => 'disabled','disabledTag' => 'a'));
            ?>
        </ul>
        <p class="small"><?= $this->Paginator->counter(['format' => __('Page {{page}} de {{pages}}, affiche {{current}} entrée(s) sur un de total {{count}}')]) ?></p>
    </div>
</div>